### ISSUE TITLE
Extension events

### ISSUE THREAD

**Issue by kfranqueiro** [dojo/core#30]
We've had a couple of discussions back and forth on the topic of extension events.  I'm opening this issue to document some of the considerations that have come up so far.
- [Extension events in Dojo 1](http://dojotoolkit.org/reference-guide/1.10/dojo/on.html#extension-events) can be kind of hard for devs to wrap their heads around (and hard for us to teach), since it involves providing a function as an event "type", and that function is in turn responsible for listening for any relevant events and firing the listener that is passed when appropriate
- The built-in extension events that exist in Dojo 1 aren't likely to be needed in Dojo 2:
  - The Pointer Events Polyfill is expected to be used in place of `dojo/touch`
  - All modern browsers support `mouseenter` and `mouseleave`
  - `a11yclick` ideally shouldn't need to exist (see https://github.com/dojo/dom/issues/10)
- That said, there are still cases where essentially "composite" events can be useful; for example, to respond to an enter keypress or a click on a row in a grid:
  
  ``` js
  function clickOrEnter(node, listener) {
      return on(node, 'click,keyup', function (event) {
          if (event.keyCode === 13 || !('keyCode' in event)) {
              listener.call(this, event);
          }
      });
  }
  
  on(document.getElementById("test"), clickOrEnter, ...);
  ```
- Another idea that has been tossed around by one or two people is instituting a registry for custom string event type names.
- One concern that has been brought up in the past is whether something could be done or a pattern promoted to minimize the number of event listeners that are actually hooked up for extension events - i.e., have a document-level handle for each type, to avoid numerous handlers being registered each time an extension event is used
- Possibly a separate consideration, but we also need to support utilities like `once` and `pausable` somehow.  While it would probably be possible to implement them via Dojo 1 style extension events, one could argue that that's muddying the waters of extension events' intended use (and personally, I'd rather see them implemented in a way that they can be used with `aspect` too).

I'm starting to throw around some examples in https://gist.github.com/kfranqueiro/b61a0d4d1939063842b2 just to illustrate different approaches.

**Comment by bryanforbes** [comment]
@kriszyp, @neonstalwart, @kitsonk, @csnover Any thoughts?

**Comment by neonstalwart** [comment]
i'm currently on medication for a toothache... there's a lot of words to comprehend here :smile: 

i always thought that extension events were a reasonably elegant mechanism to provide a way to do things which are out of the ordinary but inevitably come up from time to time.  as of this moment, i can't think of concrete cases but given that i think it's useful for those things which i don't typically think of i'd be in favor of having this kind of mechanism.

that said, i'm going to take a position i've taken a few times now... is it something that can be added later (either pre-2.0 or 2.0.x) once some concrete use cases arise to guide what it should look like?  i think it's easier to leave something out and add it later than it is to get it wrong and have to live with it.

**Comment by kitsonk** [comment]
I think I am struggling like @neonstalwart to understand the use case that would be less confusingly solved by some other pattern.  Personally I "get" synthetic events, but I have never "gotten" extension events, other than they were a way to try to "normalise" some things.  I haven't ever found myself thinking "oh, I know how to solve this problem, extension events."  (Of course, I may not have encountered problems they solve though...)

If we are saying that we believe the biggest use cases that were prevalent in Dojo 1 don't exist anymore and as Ben says, introducing that at a later date would clearly not be a breaking change, why would we tackle them now?

**Comment by kfranqueiro** [comment]
I almost had a reason to bring these back from the dead when I realized that `dojo/mouse` in Dojo 1 served a purpose beyond providing support to browsers without native `mouseenter` and `mouseleave` - it also provides support for using those events with event delegation.  However, if i'm not mistaken, this is ridiculously easy to do manually:

``` ts
delegate(rootNode, '.selector', 'mouseover', function (event) {
    if (dom.contains(this, event.target) && !dom.contains(this, event.relatedTarget)) {
        ...
    }
});
```

So, yeah.  Still don't have a use case for extension events right now, and at this point we're thinking of going ahead and removing `ExtensionEvent` from `on.ts`.
